[package]
name = "p3-challenger"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
p3-field = { path = "../field" }
p3-util = { path = "../util" }
p3-maybe-rayon = { path = "../maybe-rayon" }
p3-symmetric = { path = "../symmetric" }
tracing = { version = "0.1.37", features = ["attributes"], default-features = false }
serde = { version = "1.0", default-features = false, features = ["derive"] }

[dev-dependencies]
p3-goldilocks = { path = "../goldilocks" }
